export interface IUser {
  _id?: string; // optional, generated by MongoDB
  username: string;
  email: string;
  password: string; // hashed password
  createdAt?: Date;
  updatedAt?: Date;
  solvedPuzzles: number; // number of puzzles solved
  attempts: number; // total attempts made
}
